apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  mongo_password: YWRtaW4=
  mongo_userName: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecrets
